version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-1.4
      - test-1.5
      - test-1.6

jobs:
  test-1.4: &test-template
    docker:
      - image: circleci/elixir:1.4

    working_directory: ~/akd

    steps:
      - checkout

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test
      - run: MIX_ENV=test mix coveralls.post -t OmijPrTsGlfifPeOpKoNf763HFptPgDgf -b $(git rev-parse --abbrev-ref HEAD)
      - run: MIX_ENV=docs mix inch.report

    parallelism: 2

  test-1.5:
    <<: *test-template
    docker:
      - image: circleci/elixir:1.5

    parallelism: 2

  test-1.6:
    <<: *test-template
    docker:
      - image: circleci/elixir:1.6

    parallelism: 1
