version: 2
workflows:
  version: 2
  test:
    jobs:
      # - test-1.5
      # - test-1.6
      # - test-1.7
      # - test-1.8
      - test-1.9
      - test-1.10

jobs:
  test-1.5: &test-template
    docker:
      - image: circleci/elixir:1.5

    working_directory: ~/akd

    steps:
      - checkout

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test
      - run: MIX_ENV=test mix test
      - run: MIX_ENV=docs mix inch.report

    parallelism: 2

  test-1.9:
    <<: *test-template
    docker:
      - image: circleci/elixir:1.9

    parallelism: 2

  test-1.10:
    <<: *test-template
    docker:
      - image: circleci/elixir:1.10

    parallelism: 2
