FROM ubuntu:<%= @ubuntu_version %>

WORKDIR ~

# Update the system
RUN apt -y update && apt -y upgrade
RUN apt-get -y update && apt-get -y upgrade

# wget is a tool that can retrieve files using http, https, and ftp
RUN apt -y install wget

# Install Dev tools
RUN apt-get --fix-missing -y install build-essential m4 libncurses5-dev libssh-dev unixodbc-dev libgmp3-dev libwxgtk2.8-dev libglu1-mesa-dev fop xsltproc default-jdk
RUN apt-get -y install wxBase.x86_64

# Install Git
RUN apt-get -y install git

# Fetch and install asdf
RUN git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v<%= @asdf_version %>
RUN echo -e '\n. ~/.asdf/asdf.sh' >> ~/.bashrc
RUN echo -e '\n. ~/.asdf/completions/asdf.bash' >> ~/.bashrc
ENV PATH ~/.asdf/bin:$PATH

# Reload configurations
RUN source ~/.bashrc

# Add asdf plugins for elixir and erlang
RUN asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
RUN asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git

# Set the locale(en_US.UTF-7)
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Other Erlang Dependencies
RUN apt-get -y install build-essential
RUN apt-get -y install autoconf
RUN apt-get -y install m4
RUN apt-get -y install libncurses5-dev

# For wx Widgets of Erlang
RUN apt-get -y install libwxgtk3.0-dev libgl1-mesa-dev libglu1-mesa-dev libpng3

# More Erlang + wx Related libraries
RUN apt-get -y install libssh-dev
RUN apt-get -y install unixodbc-dev

# Install OTP <%= @erlang_version %>
RUN asdf install erlang <%= @erlang_version %>

# Install Unzip for asdf-elixir
RUN apt-get -y install unzip

# Install Elixir <%= @elixir_version %>
RUN asdf install elixir <%= @elixir_version %>

ENV PATH ~/.asdf/bin:~/.asdf/shims:$PATH

# Set versions for Elixir and Erlang
RUN asdf global elixir <%= @elixir_version %>
RUN asdf global erlang <%= @erlang_version %>

RUN elixir -v

# Get asdf completions + shims
RUN chmod +x ~/.asdf/asdf.sh
RUN chmod +x ~/.asdf/completions/asdf.bash
RUN ~/.asdf/asdf.sh
RUN ~/.asdf/completions/asdf.bash

# This is necessary for whatever reason
RUN ln -s ~/.asdf/shims/elixir /usr/bin/elixir
RUN ln -s ~/.asdf/shims/erlang /usr/bin/erlang

# Install Hex
RUN mix local.hex --force

# Install Rebar
RUN mix local.rebar --force

<%= if @with_nodejs do %>
# Install Node.js
RUN wget http://nodejs.org/dist/v<%= @nodejs_version %>/node-v<%= @nodejs_version %>-linux-x64.tar.gz
RUN tar --strip-components 1 -xzvf node-v* -C /usr/local
RUN node --version
<% end %>
